---
title: |
  | Financial Econometrics in R/Python
  | Group Assignment 2
author: |
  | Group 3
  | The Business School, Imperial College London
  | Rakesh Bali (CID: 02478023)
  | Rui Moreno (CID: 02532521)
  | Siyu Liu (CID: 02479121)
  | Zhiyu Chen (CID: 02517659)
  | Zhuofan Chen (CID: 02151338)
date: "06-11-2023"
output: pdf_document
---

```{=tex}
\newpage
\tableofcontents
```
\newpage

## Preparation of R and Data
### Loading R packages

Load the packages required.

```{r loadLibs, message=FALSE, warning=FALSE}
library(quantmod)
library(dplyr)
library(readxl)
library(moments)
library(lmtest)
library(sandwich) 
library(MASS)
library(ggplot2)
library(knitr)
library(margins)
```

### Loading Data

Load `growthdata.xlsx` into a data frame.

```{r message=FALSE, warning=FALSE}
employment_data <- read_excel("employment_08_09.xlsx")
# clean data
data <- na.omit(employment_data)
```

\newpage

## Question 1


```{r}

```

\newpage

## Question 2


```{r}

```

```{r Ada}
#%% Question b, c, d
#%% linear probability model
lpm_b <- lm(employed ~ age + I(`age`^2), data = data)
summary(lpm_b)
# probit regression
probit_c <- glm(employed ~ age + I(`age`^2), family = binomial(link = "probit"), data)
summary(probit_c)
# logit regression
logit_d <- glm(employed ~ age + I(`age`^2), family = binomial(link = "logit"), data)
summary(logit_d)

#% questions i
# t test - statistical significance of coefficients
coeftest(lpm_b, vcov = vcovHC(lpm_b), type = "HC1")
coeftest(probit_c, vcov = vcovHC(probit_c), type = "HC1")
coeftest(logit_d, vcov = vcovHC(logit_d), type = "HC1")
# marginal effects for c and d
summary(margins(lpm_b))
summary(margins(probit_c))
summary(margins(logit_d))

#% question ii
#% non-linearity evidence

# create categorical factor
# lpm_extended with factor
# lpm_interaction with factor * age
# polynomial regression = factor * age + age^2 + age^2 * factor

#% question iii

# predicted probability of b polynomial
data$employed_pred <- predict(polynomial_b, data)
# add plot

# predictions for sets of values of three models above
new_data <- data.frame(age = c(20,40,60),
                       age_sqr = c(400, 1600, 3600))  
lpm_prediction <- predict(lpm_b, new_data, type = "response")
probit_prediction <- predict(probit_c, new_data, type = "response")
logit_prediction <- predict(logit_d, new_data, type = "response")
print(list(lpm_prediction = lpm_prediction, logit_prediction = logit_prediction, probit_prediction = probit_prediction))

```

--END--
